[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]

tokio.workspace= true
serde_json.workspace = true
anyhow.workspace = true

# Reth dependencies
reth-chainspec.workspace = true
reth-tasks.workspace = true
reth-primitives.workspace = true

# Malachite dependencies

